### PR TITLE
Rubymotion 6.1 / iOS 12.2 updates

### PR DESCRIPTION
**Pull request by wndxlori**
Some updates to make motion-juxtapose work (better) with recent RM/iOS.  I was mostly fixing a problem I had (see https://github.com/terriblelabs/motion-juxtapose/pull/25/commits/ab28bc844990f756a14ea4fd350da7f6972eed5c), so I decided to cleanup/fixup everything while I was there.

### CODE REVIEW

**Comment by jeremyw** [comment]
@wndxlori Thanks, Lori! This looks awesome and it's great that this project is still providing value :)

Obviously no one has really been maintaining the project for a while. Afaik none of the original authors are still using RubyMotion. Would you be interested in taking it over?

**Comment by wndxlori** [comment]
Sure, that would be good. I’ll need access on RubyGems, too (I just mention that, since someone forgot that for another gem I took over)

**Comment by wndxlori** [comment]
So @jeremyw, can get access to this repo and push access for the gem?

**Comment by jeremyw** [comment]
@wndxlori Sorry, feel asleep at the wheel! You should have access to the repo, will get you rubygems access ASAP.

**Pull request merged**
