### PR TITLE
Support new devices

### PR DESCRIPTION
**Pull request by squidpunch**
Adds support for various device sizes. I didnt add tests though, because we'd have add a mocking framework and mock the device sizes...etc - and then its just a string compare test to the mock...
I can throw together tests if you think its needed

### CODE REVIEW

**Comment by squidpunch** [comment]
this also adds a launch screen - because otherwise we scale down to a 4s screen size.

**Comment by squidpunch** [comment]
this should fix #18

**Comment by jamonholmgren** [comment]
Nice!!

**Comment by thegreatape** [comment]
@squidpunch :+1: If it's working for you!

**Pull request merged**
